name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sleep for 120 seconds
        run: sleep 100  # 300 seconds = 5 minutes

      - name: Get PR Number
        id: pr
        run: echo "::set-output name=pr_number::${{ github.event.number }}"

      - name: Update README
        run: |
          PR_NUMBER=$(cat README.md)
          echo "PR Number: ${PR_NUMBER} (#${{ steps.pr.outputs.pr_number }})" > README.md
          git config user.name "parryk303"
          git config user.email "kyle.parry.303@gmail.com"
          git add README.md
          git commit -m "Add PR Number to README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
